### ISSUE TITLE
reduce size of .git

### ISSUE THREAD

**Issue by williamdemeo** [TypeFunc/uh-mfc#1]
A recent commit caused the repo to bloat to over 90Mb.  The large file has since been removed, but we'd like to not have it lurking in the .git history of the repo.  Let's try to delete the offending file completely, so there's no trace of it in the history.

[Here](http://stackoverflow.com/a/2158271/537578) is some advice about this.

**Comment by jfennick** [comment]
Hi,
Sorry about that.  I followed the directions [here](http://stackoverflow.com/questions/2100907/how-to-remove-delete-a-large-file-from-commit-history-in-git-repository/17890278#17890278) and it should be fixed now. Note that the install script will download several hundred megabytes, but I agree there is no need to bloat the repository for people who just want to browse the code.
